import fs from 'node:fs/promises';
import path from 'node:path';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
import {finalizePresentation,applyPresentationChartFont} from '/Users/beilakaliev/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations/container_tools/artifact_tool_utils.mjs';
const ROOT='/Users/beilakaliev/projects/qdev', WORK=ROOT+'/presentations/quantum_leap', BUILD=WORK+'/.build', OUT=WORK+'/output';
const SKILL='/Users/beilakaliev/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations';
const C={ink:'#172026',muted:'#58636D',blue:'#2463A4',amber:'#915500',paper:'#FFFFFF',pale:'#F4F6F8',rule:'#D9E0E5'};
const U={sampler:'https://quantum.cloud.ibm.com/docs/en/api/qiskit/qiskit.primitives.StatevectorSampler',runtime:'https://quantum.cloud.ibm.com/docs/en/api/qiskit-ibm-runtime/sampler-v2',account:'https://quantum.cloud.ibm.com/docs/en/guides/initialize-account',service:'https://quantum.cloud.ibm.com/docs/en/api/qiskit-ibm-runtime/qiskit-runtime-service',bits:'https://quantum.cloud.ibm.com/docs/en/guides/bit-ordering',grover:'https://quantum.cloud.ibm.com/docs/en/api/qiskit/qiskit.circuit.library.grover_operator',deprecated:'https://quantum.cloud.ibm.com/docs/api/qiskit/2.2/qiskit.circuit.library.GroverOperator',query:'https://quantum.cloud.ibm.com/learning/en/courses/fundamentals-of-quantum-algorithms/grover-algorithm/unstructured-search',vqe:'https://qiskit-community.github.io/qiskit-algorithms/stubs/qiskit_algorithms.SamplingVQE.html',qubo:'https://qiskit-community.github.io/qiskit-optimization/tutorials/03_minimum_eigen_optimizer.html',install:'https://quantum.cloud.ibm.com/docs/en/guides/install-qiskit',osprey:'https://research.ibm.com/blog/research-annual-letter-2022',migration:'https://github.com/Qiskit/documentation/blob/2d2c2fcad47dd9e7ac1cc6807527dfccd796ea24/docs/migration-guides/qiskit-runtime.mdx',repo:'https://github.com/beilak/qdev'};
const N={hello:'src/first_step/Q_Hello_World.ipynb',adder:'src/classic_on_quantum/half_adder.ipynb',vqe:'src/optimization_problem/VQE_conference.ipynb',grover:'src/grover/Grover.ipynb',tsp:'src/traveling_salesman/travel_between_city/TSP.ipynb',pythonn:'presentations/for_engineers/PythoNN/Q_PythoNN.pdf',itfest:'presentations/for_engineers/ItFest/Бейлак_Алиев_финал.pptx',old:'presentations/for_engineers/2023_first_pres/Quantum.pptx'};
const p=Presentation.create({slideSize:{width:1280,height:720}});const meta=[];
function text(s,str,x,y,w,h,size=28,color=C.ink,bold=false,font='Arial') {const t=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});t.text=str;t.text.style={typeface:font,fontSize:size,bold,color,autoFit:'none',wrap:'square',insets:{left:0,right:0,top:0,bottom:0}};return t;}
function link(s,label,url,x,y,w=1050,size=18,color=C.blue){const t=text(s,label,x,y,w,32,size,color);t.text.get(label).link={uri:url,isExternal:true};return t;}
function code(s,str,x=72,y=175,w=1136,h=380,size=24){return text(s,str,x,y,w,h,size,C.ink,false,'Courier New');}
function note(s,label,body,url){text(s,label,72,624,220,28,16,C.amber,true);text(s,body,72,651,1040,42,17,C.amber);if(url)link(s,'Documentation',url,1040,624,165,16,C.amber);}
function make(title,minutes,source,notes,kind='main'){const s=p.slides.add();s.background.fill=C.paper;const i=p.slides.items.length;text(s,title,72,54,1136,100,44,C.ink,true);text(s,String(i).padStart(2,'0'),1195,668,45,22,15,C.muted);const m={number:i,title,minutes,source,notes,kind};meta.push(m);s.speakerNotes.textFrame.setText(`Timing: ${minutes ? minutes+' minutes' : 'Backup only'}\n\n${notes}\n\nSource material: ${source}\n\nDocumentation checked: 27 September 2026. Visible amber notes are presenter review markers in this draft.`);return s;}
function table(s,values,x,y,w,h,widths,size=25){const t=s.tables.add({rows:values.length,columns:values[0].length,left:x,top:y,width:w,height:h,values,columnWidths:widths});t.borders.assign({fill:C.rule,width:1,style:'solid'});for(let r=0;r<values.length;r++)for(let c=0;c<values[0].length;c++){const cell=t.getCell(r,c);cell.fill=r===0?C.pale:C.paper;cell.text.style={typeface:'Arial',fontSize:size,color:C.ink,bold:r===0,verticalAlignment:'middle',insets:{left:14,right:12,top:9,bottom:9}};}return t;}
function bars(s,categories,series,x=72,y=185,w=720,h=350,max=1024){const ch=s.charts.add('bar',{position:{left:x,top:y,width:w,height:h},categories,series:series.map((a,i)=>({...a,fill:i?C.blue:'#708596',valuesFormatCode:'0.###',...(max===100?{dataLabelOverrides:a.values.map((v,idx)=>({idx,text:String(v)+'%',showValue:false,position:'outEnd',textStyle:{typeface:'Arial',fontSize:20,fill:C.ink}}))}:{})})),hasLegend:series.length>1,legend:{position:'bottom',textStyle:{typeface:'Arial',fontSize:20,fill:C.ink}},barOptions:{direction:'column',grouping:'clustered',gapWidth:110},xAxis:{textStyle:{typeface:'Arial',fontSize:22,fill:C.ink},line:{fill:C.rule,width:1}},yAxis:{min:0,max,majorUnit:max===100?25:256,textStyle:{typeface:'Arial',fontSize:17,fill:C.muted},majorGridlines:{fill:C.rule,width:1},numberFormatCode:'0'},dataLabels:{showValue:true,position:'outEnd',textStyle:{typeface:'Arial',fontSize:20,fill:C.ink}},chartFill:C.paper,plotAreaFill:C.paper,chartLine:{fill:'none',width:0}});applyPresentationChartFont(ch,{fontFamily:'Arial'});return ch;}
// 01
{let s=make('Quantum Leap',.5,`${N.pythonn}, p. 1; supplied conference title`,'Opening: “I will show you a small quantum program, read its output, and show the same workflow on a real device.” State that Python knowledge is enough. Avoid promises about business speedups.');text(s,'Building Real Quantum\nPrograms with Python',72,218,1080,180,54,C.ink);text(s,'Beilak Aliev',72,504,800,50,28,C.muted);text(s,'Conference draft / 27 September 2026',72,643,1050,35,18,C.muted);}
// 02
{let s=make('A quantum program in Python',1,`${N.hello}, cells 4, 6, 7; ${N.vqe}, cells 11–12`,'Python constructs and submits a circuit. A simulator computes its behavior on a classical machine. A quantum processor executes the compiled gates. Both return measurement samples. A shot means one circuit execution followed by measurement. Transition: what do the gates act on?');table(s,[['Python','Execution','Result'],['QuantumCircuit','Local simulator','Counts of bitstrings'],['The same circuit model','Cloud quantum processor','Counts + job metadata']],72,190,1136,240,[378,379,379],28);text(s,'One shot = one execution and measurement',72,492,1120,60,32);}
// 03
{let s=make('Qubits and measurement',2,`${N.pythonn}, pp. 5–8; ${N.old}, slide 7; ${N.hello}, cell 4`,'A qubit can have complex amplitudes alpha and beta. Their squared magnitudes determine measurement probabilities. The H gate on a zero input gives equal probabilities. Measurement returns one classical bit. Explain phase only as a property gates can use to change later probabilities. Do not say the machine reads every answer simultaneously. The old “greater capacity” phrase hides this distinction.');text(s,'State:  α|0⟩ + β|1⟩',72,184,1050,70,46);text(s,'P(0) = |α|²       P(1) = |β|²',72,284,1100,65,36);text(s,'After H on |0⟩: 50% 0, 50% 1',72,395,1100,60,34,C.blue);text(s,'Each measurement gives one bit.',72,494,1100,55,30);note(s,'CORRECTION','The old “greater capacity” wording needs this measurement qualification.');}
// 04
{let s=make('The gates used in these notebooks',1.5,`${N.adder}, cells 4–5; ${N.hello}, cell 4; ${N.vqe}, cells 2–5`,'X flips a computational-basis value. H prepares equal probabilities from zero. CX flips its target when its control is one, stated for basis inputs. It can create entanglement on a superposed control. CCX has two controls. RY uses an adjustable angle. CZ changes a phase and can entangle suitable inputs. Avoid implying that CX copies arbitrary unknown quantum states.');table(s,[['Gate','Role in our examples'],['X','Flip 0 and 1'],['H','Prepare superposition from 0'],['CX / CCX','Flip a target under one / two controls'],['RY(θ) / CZ','Adjust a trial state / apply a controlled phase']],72,175,1136,370,[250,886],27);}
// 05
{let s=make('A half-adder',1.5,`${N.adder}, cells 3–6`,'Use ordinary binary addition as a bridge. Inputs stay in q0 and q1. q2 stores the XOR sum and q3 stores the AND carry, both starting at zero. The notebook measures q2 into c0 and q3 into c1. Qiskit prints c1c0, hence 1+1 gives 10. This circuit demonstrates reversible logic, without a speedup claim. Local rehearsal checked all four input cases.');code(s,'qc = QuantumCircuit(4, 2)\nqc.x(0)\nqc.x(1)\nqc.cx(0, 2)\nqc.cx(1, 2)\nqc.ccx(0, 1, 3)\nqc.measure([2, 3], [0, 1])',72,184,670,330,26);text(s,'1 + 1 = 10',806,215,400,80,48,C.blue,true);text(s,'c1 = carry\nc0 = sum',808,325,385,100,30);note(s,'BIT ORDER','Displayed “10” means carry = 1 and sum = 0.',U.bits);}
// 06
{let s=make('Hello World: three correlated qubits',2,`${N.hello}, cell 4; ${N.pythonn}, p. 10; ${N.itfest}, slide 10`,'Build the exact three-qubit circuit from the supplied Hello World notebook. H prepares the first qubit. Each CX correlates another qubit. Before measurement the ideal circuit prepares the GHZ state (|000> + |111>)/sqrt(2), which is entangled. The older decks use the two-qubit Bell version. Distinguish these variants. Computational-basis counts alone do not certify entanglement because a classical mixture can give the same histogram.');code(s,'from qiskit import QuantumCircuit\n\nqc = QuantumCircuit(3)\nqc.h(0)\nqc.cx(0, 1)\nqc.cx(0, 2)\nqc.measure_all()',72,175,770,360,27);text(s,'Ideal outcomes',900,208,310,45,24,C.muted);text(s,'000\n111',900,283,310,170,52,C.blue,true);text(s,'The circuit prepares an entangled GHZ state.',72,549,1120,50,29);}
// 07
{let s=make('Local simulation',2,`${N.hello}, cell 6, migrated using StatevectorSampler already used in ${N.vqe}, cell 7`,'Run the circuit from the previous slide. StatevectorSampler is a local ideal simulator in Qiskit. It produces sampled counts. measure_all creates the register named meas, which explains data.meas. The half-adder has register c instead, so use data.c for that circuit. Show this run live, allow about one minute including a question about expected counts. Documentation: '+U.sampler);code(s,'from qiskit.primitives import StatevectorSampler\n\nsampler = StatevectorSampler(seed=42)\njob = sampler.run([qc], shots=1024)\ncounts = job.result()[0].data.meas.get_counts()\nprint(counts)',72,190,1136,300,27);text(s,'1,024 shots sample the output distribution.',72,515,1136,55,29);note(s,'UPDATE','Replaces the old “from qiskit import Aer” execution path.',U.sampler);}
// 08
{let s=make('Reading the counts',1.5,`${N.hello}, cell 6, saved output`,'The notebook saved 537 occurrences of 000 and 487 of 111, totaling 1,024. This is a historical simulator result. An ideal circuit gives equal probabilities, but finite counts need not match. The updated local rehearsal gave 515 and 509. Never present either histogram as fresh hardware data. Ask why 001 is absent in the ideal simulator. Note that noise can introduce other strings on a device.');bars(s,['"000"','"111"'],[{name:'Saved simulator run',values:[537,487]}]);text(s,'537 + 487\n= 1,024 shots',865,245,335,120,34);text(s,'50/50 describes\nprobabilities.',865,414,335,115,28,C.muted);note(s,'SAVED RUN','Counts from Q_Hello_World.ipynb. Rerunning gives a new sample.');}
// 09
{let s=make('A two-bit optimization problem',2,`${N.vqe}, cells 1–3`,'Introduce the supplied objective and enumerate four possibilities so the audience knows the correct answer before discussing VQE. q0 represents a and q1 represents b. 01 therefore means a=1 and b=0, with objective 3. Enumeration is the classical reference for this toy problem. The exercise shows the mechanism of a variational algorithm.');text(s,'Maximize  f(a, b) = 3a + 2b − 4ab',72,163,1136,65,36);table(s,[['a','b','Displayed q1q0','f(a, b)'],['0','0','00','0'],['1','0','01','3'],['0','1','10','2'],['1','1','11','1']],72,254,740,310,[110,110,300,220],27);text(s,'Best assignment\na = 1, b = 0',860,304,345,120,33,C.blue);note(s,'BIT ORDER','The rightmost displayed bit is q0, which represents a.',U.bits);}
// 10
{let s=make('The VQE feedback loop',2,`${N.vqe}, cells 2, 4, 6–7`,'VQE means Variational Quantum Eigensolver. An ansatz is an adjustable trial circuit. The notebook uses RY rotations and CZ gates. SamplingVQE estimates a diagonal Ising cost from sampled outcomes. COBYLA changes angles on the classical CPU. The model conversion turns maximization into energy minimization. CZ is a circuit design choice: the ab term does not itself require an entangled optimal state. Here the optimum is a basis state. Documentation: '+U.vqe);table(s,[['Step','Where it runs'],['Choose circuit angles','Classical optimizer'],['Prepare and measure the trial state','Simulator or quantum processor'],['Estimate cost and update angles','Classical optimizer']],72,182,1136,310,[770,366],28);text(s,'Repeat until the evaluation budget ends.',72,535,1136,55,29);}
// 11
{let s=make('VQE in the supplied notebook',1.5,`${N.vqe}, cells 2, 7`,'This is the central loop, with model construction and imports in the notebook and rehearsal script. small_problem is the objective on slide 9. cost_operator and small_ansatz come from cell 2. Show the seed and evaluation budget. The run uses 1,024 shots per sampled energy estimate and a COBYLA budget of 20 evaluations. The sampled cost need not improve at every evaluation. Run the supplied local rehearsal if there is time. Documentation: '+U.vqe);code(s,'algorithm_globals.random_seed = 1234\nsmall_vqe = SamplingVQE(\n    sampler=StatevectorSampler(\n        default_shots=1024, seed=1234),\n    ansatz=small_ansatz,\n    optimizer=COBYLA(maxiter=20),\n)\nsmall_result = small_vqe.compute_minimum_eigenvalue(\n    cost_operator)',72,164,1136,425,25);note(s,'CURRENT PATTERN','This notebook already uses V2 sampling. Imports and model setup are in VQE_conference.ipynb.',U.vqe);}
// 12
{let s=make('The measured answer',1.5,`${N.vqe}, cells 7–9, saved output`,'The saved simulator output has 984 occurrences of 01 out of 1,024. Group the remaining 40 under Other because the saved text explicitly reports the mode, not each remaining count. The most frequent bitstring directly decodes to the optimum. This differs from selecting a rare good candidate from many samples. Local rehearsal reproduced 984/1024 in this environment.');bars(s,['"01"','Other'],[{name:'Saved simulator run',values:[984,40]}]);text(s,'01',877,214,300,80,60,C.blue,true);text(s,'a = 1, b = 0\nf(1, 0) = 3',877,334,325,130,33);note(s,'SAVED RUN','984 of 1,024 measurements give the optimal assignment in this run.');}
// 13
{let s=make('Submitting a cloud job',2.5,`${N.vqe}, cell 11; execution pattern from ${N.hello}, cell 7`,'Prerequisite: configure an IBM Quantum Platform account and an accessible service instance using current instructions. QiskitRuntimeService() loads the saved account. Bind the trained angles before hardware execution: measured_circuit = small_ansatz.assign_parameters(small_result.optimal_point), then measured_circuit.measure_all(). Compile for the selected backend and submit one SamplerV2 job. Print and save job.job_id(). Read counts with job.result()[0].data.meas.get_counts(). Do not wait for a queue on stage. The supplied notebook defaults to retrieval of its existing job. No new QPU job was submitted while preparing this deck. Current account guide: '+U.account+'\nSampler API: '+U.runtime+'\nService API: '+U.service);code(s,'from qiskit_ibm_runtime import (\n    QiskitRuntimeService, SamplerV2,\n)\nfrom qiskit.transpiler.preset_passmanagers import (\n    generate_preset_pass_manager,\n)\n\nservice = QiskitRuntimeService()\nbackend = service.least_busy(\n    operational=True, simulator=False,\n    min_num_qubits=2)',72,172,672,378,20);code(s,'# measured_circuit has fixed angles\npm = generate_preset_pass_manager(\n    backend=backend,\n    optimization_level=3,\n)\nisa = pm.run(measured_circuit)\njob = SamplerV2(mode=backend).run(\n    [isa], shots=1024,\n)\nprint(job.job_id())',764,172,475,378,20);note(s,'CHECK BEFORE TALK','Account, instance access, backend availability and queue. Use saved results on stage.',U.account);}
// 14
{let s=make('The saved hardware result',1.5,`${N.vqe}, cells 11–13`,'These counts come from the saved output of job dasegqjojkfs738p8fng on ibm_marrakesh. They were not fetched again for this draft. The angles were optimized on the local simulator and held fixed on the device. This is one hardware sampling job, not full VQE training on a QPU. 986 versus 984 occurrences of the mode does not establish a fidelity improvement or quantum advantage. Recheck the job metadata and backend name before the talk.');bars(s,['"00"','"01"','"10"','"11"'],[{name:'ibm_marrakesh',values:[7,986,13,18]}],72,187,740,350);text(s,'01: 986 / 1,024',852,229,360,80,32,C.blue,true);text(s,'Local simulator:\n984 / 1,024',852,341,360,105,28);text(s,'Angles trained locally',852,496,360,65,25,C.muted);note(s,'SAVED RUN','ibm_marrakesh. Fixed trained circuit, one sampling job. Recheck job metadata.');}
// 15
{let s=make('Grover: increasing a target probability',1.5,`${N.grover}, cells 5–8; ${N.itfest}, slides 12–17`,'Use the supplied three-qubit target 010. The initial distribution assigns probability 1/8 to every string. The notebook applies one Grover iteration. An exact local statevector calculation gives 25/32 = 78.125% for 010. The target is built into a toy oracle. This example does not load or search a Python database. The asymptotic O(sqrt(N)) statement concerns oracle queries under the search model. Oracle implementation and data loading cost still matter. Documentation: '+U.grover+'\nQuery model: '+U.query);bars(s,['Before','After one iteration'],[{name:'P(010), percent',values:[12.5,78.125]}],72,200,725,330,100);text(s,'Target: 010\nEight possible strings',854,230,360,130,31);text(s,'Ideal probabilities (%)\ncalculated from this circuit',854,426,360,110,24,C.muted);note(s,'UPDATE','GroverOperator is deprecated. Use grover_operator. Oracle queries are the complexity unit.',U.grover);}
// 16
{let s=make('Route optimization with QAOA',1.5,`${N.tsp}, cells 1, 3, 5, 9`,'The current graph uses seven cities and eight directed edges, so the edge-based QUBO has eight binary variables and eight qubits. Start Moscow, end Florianopolis, with Baku required. The cheapest route follows Moscow, Baku, Doha, Florianopolis with toy cost 4+2+5=11. The notebook saved a successful candidate but only about 1.9% of all samples were feasible. Its text describes an older graph and seven qubits, which needs correction. The current code has no executed NetworkX baseline comparison despite its narrative promise. We independently enumerated the three feasible paths for this small graph: costs 11, 12, 12.');text(s,'Moscow / Baku / Doha / Florianópolis',72,177,1136,65,38);text(s,'Illustrative cost: 4 + 2 + 5 = 11',72,275,1136,60,32,C.blue);table(s,[['Encoding','Saved sample distribution'],['8 edges = 8 binary variables = 8 qubits','1.9% feasible outcomes']],72,386,1136,136,[650,486],26);note(s,'CORRECTION','TSP.ipynb solves a constrained shortest path. Its prose still describes an older graph.',U.qubo);}
// 17
{let s=make('What these examples establish',1,`${N.hello}, ${N.vqe}, ${N.grover}, ${N.tsp}`,'Summarize what the supplied evidence actually supports. The circuits run and produce samples. A tiny objective can yield a dominant optimum in the saved VQE run. The saved hardware experiment executes fixed angles on a device. Grover illustrates amplitude amplification under a toy oracle. The route example exposes constraint handling and poor feasible sampling. None of these establishes a speed advantage. Keep this limit concise and tied to the examples.');table(s,[['Example','What we can observe'],['Hello World','Correlated measurement outcomes'],['VQE','A dominant optimum in one small run'],['Cloud execution','Samples from a real device'],['QAOA route','A feasible answer amid many invalid samples']],72,181,1136,350,[350,786],27);text(s,'These small runs do not establish quantum advantage.',72,567,1136,52,28,C.muted);}
// 18
{let s=make('Code and questions',.5,'All five supplied notebooks; project repository linked in the source notebooks','Closing: “You can build a circuit, sample it locally, and submit its compiled version to a quantum processor. The result is a distribution you need to interpret.” Point to the supplied repository. The GitHub link comes from the notebooks, but the current uncommitted notebook versions may not be published. Before sharing it publicly, verify that the exact rehearsal material is available at the intended revision. Invite questions.');text(s,'github.com/beilak/qdev',72,214,1136,80,48,C.blue);link(s,'Notebook repository',U.repo,72,314,1000,27);text(s,'Questions',72,468,1136,85,48);note(s,'CHECK BEFORE TALK','Confirm that the public repository contains the exact notebook versions you will present.');}
// 19
{let s=make('Backup: the larger VQE example',0,`${N.vqe}, cells 14–20`,'Five model variables comprise three binary choices plus two bounded integers. QUBO conversion introduces a total of fourteen binary variables. The saved solution is x1=1, x2=1, x3=0, x4=10, x5=5, objective 47. The constraint requires x4+x5 >= 15. This optimum can be verified directly for the toy model. MinimumEigenOptimizer chooses the best feasible decoded sample. The notebook states that the returned assignment is rare, but does not save a numerical frequency for it. Do not invent one or say that the modal string represents this answer.','backup');text(s,'5 model variables / 14 encoded qubits',72,187,1136,65,36);text(s,'Saved assignment: (1, 1, 0, 10, 5)',72,295,1136,60,32);text(s,'Objective: 47',72,395,1136,65,40,C.blue);text(s,'Best feasible sampled candidate can differ from\nthe most frequent bitstring.',72,492,1136,95,29);note(s,'INTERPRETATION','A printed optimum alone does not show that the circuit concentrates on that answer.',U.qubo);}
// 20
{let s=make('Backup: API changes to review',0,'Legacy cells in Hello World, half_adder and Grover. Modern cells in VQE and TSP.','The deprecated qiskit-ibm-provider / backend.run path applies to IBM cloud execution. Do not generalize the removal to every backend or to local Aer. Aer remains a separate simulator package. The draft uses StatevectorSampler for the ideal local examples, matching the current VQE notebook. qiskit[optimaze] in Grover is an invalid extra, not a valid dependency choice. Legacy Colab badges point to paths without src and should be checked. GroverOperator remains available in the installed 2.5.2 environment but is deprecated. Documentation: '+U.install+'\n'+U.sampler+'\n'+U.runtime+'\n'+U.deprecated,'backup');table(s,[['In the old material','Pattern used in this draft'],['from qiskit import Aer','StatevectorSampler for ideal sampling'],['IBMProvider + backend.run','QiskitRuntimeService + SamplerV2'],['GroverOperator(...)','grover_operator(...)'],["qiskit['optimaze']",'Use explicit supported packages']],72,176,1136,353,[558,578],25);note(s,'UPDATE','Check the rehearsed environment after any package update.',U.install);}
// 21
{let s=make('Backup: content that needs review',0,`${N.old}, slides 5, 7–9, 16; ${N.itfest}, slides 3, 7; ${N.pythonn}, pp. 3, 7, 12; ${N.tsp}, markdown cells`,'The older material includes historical hardware counts, job titles, contact details and broad QML labels. Osprey had 433 qubits in 2022. The ItFest timeline associates that figure with 2024, which should be corrected. Do not substitute a new largest-qubit claim unless needed and verified. The qubit wording needs measurement probabilities. The QML/QNN teaser has no corresponding implementation in the five supplied notebooks, so it is outside the core talk. The route markdown needs the current seven-city, eight-edge graph. The VQE claim that an ab interaction gives entanglement a necessary role is too strong: this optimum is a product basis state.','backup');table(s,[['Item','Action before presenting'],['433 qubits / Osprey','Historical: 2022. Correct the ItFest date.'],['“Greater capacity”','Explain amplitudes and one-bit measurement.'],['TSP text / seven qubits','Use shortest path / eight qubits.'],['QML labels, biography, contacts','Review relevance and current details.']],72,176,1136,353,[410,726],25);note(s,'CHECK BEFORE TALK','Hardware counts and old dates describe historical material.',U.osprey);}
// 22
{let s=make('Reference links',0,'Official documentation used only to check and update supplied material','These links support migration and accuracy checks, not additional case studies. Checked 27 September 2026. The detailed source audit maps findings to the supplied notebook cells and old slides. The legacy migration guide is archived and serves as evidence of the removed IBM execution path. Use current API pages for implementation.\n'+Object.entries(U).map(([k,v])=>k+': '+v).join('\n'),'backup');const refs=[['Qiskit installation and supported environment',U.install],['Local sampling and measurement results',U.sampler],['IBM account setup',U.account],['SamplerV2 cloud execution',U.runtime],['SamplingVQE',U.vqe],['QUBO conversion and sample interpretation',U.qubo],['Grover operator and query model',U.grover],['Qiskit bit ordering',U.bits]];refs.forEach(([a,b],i)=>link(s,a,b,72,167+i*51,1136,25));text(s,'Checked 27 September 2026',72,633,1120,35,18,C.muted);}
await fs.writeFile(BUILD+'/slides.json',JSON.stringify(meta,null,2));
await fs.writeFile(BUILD+'/links.json',JSON.stringify(U,null,2));
const candidate=BUILD+'/candidate.pptx';await(await PresentationFile.exportPptx(p)).save(candidate);
for(let i=0;i<p.slides.items.length;i++){const s=p.slides.items[i];const png=await p.export({slide:s,format:'png',scale:1});await fs.writeFile(BUILD+`/slide-${String(i+1).padStart(2,'0')}.png`,new Uint8Array(await png.arrayBuffer()));}
const result=await finalizePresentation({workspaceDir:WORK,candidatePath:candidate,finalPath:OUT+'/Quantum_Leap_Draft_v3.pptx',pythonExecutable:'/Users/beilakaliev/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3',integrityValidatorPath:SKILL+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:SKILL+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...[2,4,9,10,16,17,20,21].flatMap(n=>['--require-native-table-slide',String(n)])],requiredNativeTableOwnerSlides:[2,4,9,10,16,17,20,21],requiredNativeChartOwnerSlides:[8,12,14,15],materializeLiteralChartWorkbooks:true,fontPolicy:{basis:'design',families:['Arial','Courier New']},verifyArtifactToolImport:true,receiptPath:BUILD+'/validation-v3.json'});console.log(JSON.stringify(result));
